Revert "added standard V0 cuts"
This reverts commit 94734805ef7daaf80b0d501bdc6215ba9d0d2107.

This does not compile with error:

    PWGLF/SPECTRA/IdentifiedHighPt/train/AliAnaTaskV0EffDecomposition.h:53:43: error: 'fMinPt' was not declared in this scope

Most likely cause it's simply missing a `double fMinPt` in the class
declaration.