dynamic cast replaced by static cast in order to avoid undefined reference to typinfo of AliGenMC. Correct initialization of the new member of AliGenMC.