Revert "added standard V0 cuts"
This reverts commit 6b21dec7a9a0195323296d2c4f766be84defd923.

This does not compile with error:

    PWGLF/SPECTRA/IdentifiedHighPt/train/AliAnaTaskV0EffDecomposition.h:53:43: error: 'fMinPt' was not declared in this scope

Most likely cause it's simply missing a `double fMinPt` in the class
declaration.