Remove includes since ESD MC trains cannot run with Root 6
In file included from input_line_79:1:
In file included from /home/alitrain/train-workdir/PWGCF/CF_pp_MC_ESD/247_20190925-2122/config/handlers.C:5:
/cvmfs/alice.cern.ch/el6-x86_64/Packages/AliRoot/v5-09-50_ROOT6-1/ANALYSIS/macros/train/AddMCHandler.C:1:20: error: definition with same mangled name as another definition
AliMCEventHandler* AddMCHandler(Bool_t readTrackRef = kFALSE)
                   ^
/cvmfs/alice.cern.ch/el6-x86_64/Packages/AliRoot/v5-09-50_ROOT6-1/ANALYSIS/macros/train/AddMCHandler.C:1:20: note: previous definition is here
AliMCEventHandler* AddMCHandler(Bool_t readTrackRef = kFALSE)